name: Build Workspace Context Server and Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: server-cache
    - name: Build server
      run: cargo build --release
    - name: Upload server artifact
      uses: actions/upload-artifact@v4
      with:
        name: workspace-server-${{ github.sha }}
        path: target/release/workspace
        retention-days: 30

  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Add wasm32-wasip1 target
      run: rustup target add wasm32-wasip1
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: extension-cache
        workspaces: workspace-context
    - name: Build extension
      working-directory: workspace-context
      run: cargo build --release --target wasm32-wasip1
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: workspace-extension-${{ github.sha }}
        path: workspace-context/target/wasm32-wasip1/release/workspace_context.wasm
        retention-days: 30